apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod-logging
spec:
  volumes:
    - name: varlog
      emptyDir: {}
  containers:
    - image: nginx
      name: nginx-pod
      resources: {}
      volumeMounts:
        - name: varlog
          mountPath: /var/log/nginx
    - name: sidecar-container
      image: busybox:1.28
      command:
        [
          "sh",
          "-c",
          "while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done",
        ]
      volumeMounts:
        - name: varlog
          mountPath: /var/log/nginx
