apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: titan
  name: titan
spec:
  replicas: 10
  selector:
    matchLabels:
      app: titan
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: titan
    spec:
      runtimeClassName: gvisor
      containers:
        - image: swarntech/titan:6b2b47e
          name: titan
          ports:
            - containerPort: 3000
          resources: {}
status: {}
