apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: titan
  name: titan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titan
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: titan
    spec:
      runtimeClassName: gvisor
      containers:
        - image: swarntech/titan:6b2b47e
          name: titan
          ports:
            - containerPort: 3000
          resources: {}
status: {}
