apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: initializer
  name: initpod
spec:
  initContainers:
    - image: busybox:1.28.4
      name: init-cont
      command:
        [
          "sh",
          "-c",
          "until nslookup k8sbook; do echo waiting for k8sbook service; sleep 1; done; echo Service found!",
        ]
  containers:
    - name: web-ctr
      image: nigelpoulton/web-app:1.0
      ports:
        - containerPort: 808
